echo y env falta normi y liberar memoria de la lista
migueldar/42minishell pull request #14
Opened 2023-08-15 15:00 UTC by luciamar1

2023-08-15 15:12 UTC, migueldar requested changes

2023-08-15 15:12 UTC, migueldar commented on env_list.c
> +t_list	*ft_lstnew(void *content)
cogelo de la libft

2023-08-15 15:12 UTC, migueldar commented on libft/Makefile
> +CFLAGS =-Wall -Wextra -Werror
quita este cambio (vuelve a meter el espacio)

2023-08-15 15:12 UTC, migueldar commented on utils_lucia_y_el_uraño.c
> +}
cambia el nombre de este archivo

2023-08-15 15:12 UTC, migueldar commented on env_list.c
> +        perror("fallo de malloc key");
no tires fallos con perror

2023-08-15 15:12 UTC, migueldar commented on env_list.c
> +    if(key_value->key == NULL)
el valor del que estas comprobando si es null deberia ser key_value->value, no key_value->key

2023-08-15 15:12 UTC, migueldar commented on env_list.c
> +}
Toda la gestion de mallocs es incorrecta, utiliza las funciones de las que te he hablado para ir petando los mallocs uno a uno y ver si tienes leaks. Si quieres puedes hacer un rebase de master para pillar todas las funciones de malloc debug. Con eso consigues que si haces
`make malloc_debug when=$numero_de_malloc_quieres_petar`
te va a petar el malloc de forma selectiva cuando corras el programa

2023-08-15 15:12 UTC, migueldar commented on builtins
elimina esto

2023-08-15 15:12 UTC, migueldar commented on Makefile
esta makefile se implemetara en la version cuando partamos todo en carpetas, ahora no. Si quieres commitearla aun asi cambiale el nombre (Makefile2) para tenerla, pero no me gusta tener pusheadas en el git este tipo de cosas.

2023-08-15 15:21 UTC, migueldar commented on builtins.h
> +}t_env;
cambiar esto para ser compatible con libft

2023-08-16 10:19 UTC, luciamar1 commented on env_list.c
> +t_list	*ft_lstnew(void *content)
hecho

2023-08-16 10:19 UTC, luciamar1 commented on libft/Makefile
> +CFLAGS =-Wall -Wextra -Werror
hecho

2023-08-16 10:19 UTC, luciamar1 commented on utils_lucia_y_el_uraño.c
> +}
hecho

2023-08-16 10:19 UTC, luciamar1 commented on env_list.c
> +        perror("fallo de malloc key");
hecho=)

2023-08-16 10:19 UTC, luciamar1 commented on env_list.c
> +    if(key_value->key == NULL)
glasias=)

2023-08-16 10:20 UTC, luciamar1 commented on env_list.c
> +}
me falta aunq he gestionado los mallocs luego lo pruebo

2023-08-16 10:20 UTC, luciamar1 commented on Makefile
hecho

2023-08-16 10:20 UTC, luciamar1 commented on builtins.h
> +}t_env;
hecho=)

2023-08-16 14:19 UTC, migueldar requested changes

2023-08-16 14:19 UTC, migueldar commented on built-ins/cd.c
este archivo no tiene que ver con esta pull request, tienes que subirlo luego en otra pull request

2023-08-16 14:19 UTC, migueldar commented on built-ins/echo.c
este archivo no tiene que ver con esta pull request, tienes que subirlo luego en otra pull request

2023-08-16 14:19 UTC, migueldar commented on built-ins/env.c
este archivo no tiene que ver con esta pull request, tienes que subirlo luego en otra pull request

2023-08-16 14:19 UTC, migueldar commented on built-ins/pwd.c
este archivo no tiene que ver con esta pull request, tienes que subirlo luego en otra pull request

2023-08-16 14:19 UTC, migueldar commented on built-ins/utils_builtins.c
este archivo no tiene que ver con esta pull request, tienes que subirlo luego en otra pull request

2023-08-16 14:19 UTC, migueldar commented on libft/Makefile
> +CFLAGS =-Wall -Wextra -Werror
no lo has corregido

2023-08-16 14:19 UTC, migueldar commented on env_list.c
este archivo eliminalo en el commit final, ya que no es el que vamos a usar

2023-08-16 14:19 UTC, migueldar commented on env_list_libft.c
cambia el nombre del archivo a env_list.c

2023-08-16 14:19 UTC, migueldar commented on env_list_libft.c
> +void	ft_free_env_value(void *env_value)
haz que esta funcion acepte un t_env_var* en vez de un void*, y cambia su nombre a free_env_var

2023-08-16 14:19 UTC, migueldar commented on env_list_libft.c
> +}
lo que haces en esta funcion de primero llenar todo con lst_new(NULL) es una chapuza, solo debe haber un bucle por el que se itere y se vaya llenando la lista, utilizando lstadd_back. Por favor haz algo parecido a lo que te mostre ayer, lo tienes en tokenizer.c. Ya te lo he explicado, cuando nos encontramos un problema intentamos entender porque es y como solucionarlo, no buscamos atajos.

2023-08-16 14:19 UTC, migueldar commented on env_list_libft.c
> +	while(head)
este printeo aqui es una chapuza, no se puede commitear a master. Ademas esta funcion tiene que devolver la t_env, no llenarla.

2023-08-16 14:19 UTC, migueldar commented on env_list_libft.c
> +	write(2, "malloc env fail in env\n", 16);
no puedes printear esto al liberar. Recuerda que esta lista se liberara al final del programa y no queremos que nos printee un malloc fail. El mensaje de printeo, cuando lo pongas, debe ser simplemente "Malloc fail", pero bueno ya te dije ayer que por tema printeo no te rayes mucho porque seguramente tengamos que cambiar toda la estructura de printeos en algun momento.

2023-08-16 14:19 UTC, migueldar commented on env_list_libft.c
> +	env_value = ft_calloc(sizeof(t_env_var *), 1);
te sobra el puntero ahi, es sizeof t_env_var, no sizeof t_env_var*. Ademas, calloc es al reves, primero cantidad y luego size (osea lo correcto es ft_calloc(1, sizeof(t_env_var)) , cuestion de limpieza.

2023-08-16 14:19 UTC, migueldar commented on env_list_libft.c
> +}
estoy bastante seguro de que aun guardas el = en la key o el value, por favor quitalo

2023-08-16 15:12 UTC, luciamar1 commented on env_list_libft.c
> +}
hecho

2023-08-16 15:29 UTC, luciamar1 commented on env_list_libft.c
> +}
cuando pongo env ++ es para correr la direccion de memoria de env que en ese momento es '=' y correrla una mas para pasarselo a la funcion que va a copiar el contenido de value

2023-08-16 17:48 UTC, migueldar requested changes

2023-08-16 17:48 UTC, migueldar commented on libft/libft.h.gch
quita esto

2023-08-16 17:48 UTC, migueldar commented on a.out
quita esto

2023-08-16 17:48 UTC, migueldar commented on env_list.c
> +void	ft_free_env_value(void *env_value)
haz que esta funcion acepte un t_env_var* en vez de un void*, y cambia su nombre a free_env_var

2023-08-16 17:48 UTC, migueldar commented on env_list.c
> +	env_value = ft_calloc(1, sizeof(t_env_var));
malloc no protegido

2023-08-16 17:48 UTC, migueldar commented on env_list.c
> +	if (env_value->key == NULL)
cuando falla este malloc tienes que liberar el env_value tambien

2023-08-16 17:48 UTC, migueldar commented on env_list.c
> +	env_value->value = ft_calloc(length, sizeof(char));
cuando falla este malloc tienes que liberar el env_value->key y el env_value tambien

2023-08-16 17:48 UTC, migueldar commented on env_list.c
> +		if (!new || new->content == NULL)
esta comprobacion debe ser simplemente if !new

2023-08-16 17:51 UTC, luciamar1 commented on env_list.c
> +		if (!new || new->content == NULL)
es que puede fallar el malloc de create env value

2023-08-16 17:52 UTC, luciamar1 commented on env_list.c
> +	env_value->value = ft_calloc(length, sizeof(char));
lo hago en free_env_l

2023-08-16 17:53 UTC, luciamar1 commented on env_list.c
> +	env_value->value = ft_calloc(length, sizeof(char));
huy en ft_create_list

2023-08-16 17:55 UTC, luciamar1 commented on env_list.c
> +void	ft_free_env_value(void *env_value)
hecho

2023-08-16 18:13 UTC, migueldar commented on env_list.c
> +	env_value->value = ft_calloc(length, sizeof(char));
no lo estas liberando en ft_create_list. Aun asi, no seria correcto hacerlo ahi(audio en wassap)

2023-08-16 18:33 UTC, migueldar requested changes

2023-08-16 18:33 UTC, migueldar commented on env_list.c
> +	t_env_var	*k_v_to_free;
esto ya no hace falta, porque la variable que te pasan ya es del tipo que necesitas

2023-08-16 18:33 UTC, migueldar commented on env_list.c
> +	if(k_v_to_free->key)
no hacen falta estos if, pero si que deberias poner un if (env_value))

2023-08-16 18:33 UTC, migueldar commented on env_list.c
> +		return (ft_free_env_var(env_value), NULL);
pon simplemente un free(env_value)

2023-08-16 18:55 UTC, migueldar requested changes

2023-08-16 18:55 UTC, migueldar commented on env_list.c
> +void	*free_env_l(t_env **envi)
quita esta funcion, hazlo directamente como te pongo abajo

2023-08-16 18:55 UTC, migueldar commented on env_list.c
> +			return (free_env_l(&envi));
return (ft_lstclear((t_list **) &envi, (void (*)(void *)) free_env_var), NULL);

2023-08-16 18:55 UTC, migueldar commented on env_list.c
> +	envi = ((counter = 0), NULL);
evita esto, te sobran lineas

2023-08-16 19:49 UTC, merged