Find path
migueldar/42minishell pull request #47
Opened 2023-09-16 20:31 UTC by luciamar1

2023-09-19 19:40 UTC, migueldar requested changes

2023-09-19 19:40 UTC, migueldar commented on src/env/env_utils.c
> +int	leng_env(t_env *env)
ya existe lstsize y es la que usas en el codigo, borra esto

2023-09-19 19:40 UTC, migueldar commented on src/executer/executer_utils.c
> +	printf("hola\n");
quitalo

2023-09-19 19:40 UTC, migueldar commented on src/executer/executer_utils.c
> +	printf("adios\n");
quitalo

2023-09-19 19:40 UTC, migueldar commented on src/utils/utils2.c
>  //return NULL if fail
borra estas lineas de comentarios, ahora que has movido el get_env sobran

2023-09-19 19:40 UTC, migueldar commented on log
quitalo

2023-09-19 19:40 UTC, migueldar commented on logerr
quitalo

2023-09-19 19:40 UTC, migueldar commented on lib/structs.h
> +typedef struct s_executer
esto quitalo que no lo vamos a usar

2023-09-21 13:29 UTC, luciamar1 commented on log
el que ?

2023-09-21 22:56 UTC, migueldar approved these changes

2023-09-21 22:56 UTC, merged